name: PR

on:
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    strategy:
      matrix:
        exercises: ['day00', 'day01', 'day02', 'day03', 'day04', 'day05']

    uses: ./.github/workflows/build-and-test.yml
    with:
      exercise: 'exercise/ts/${{matrix.exercises}}'
